[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"


[project]
name = "rutgers-robot-inference"
version = "0.1.0"
description = "A minimal inference stack for robot policies."
readme = "readme.md"
requires-python = ">=3.10"
license-files = ["THIRD_PARTY_NOTICES.md", "licenses/*"]

dependencies = [
    "numpy",
    "pyzmq",
    "msgpack",
]


[project.optional-dependencies]
client = [
    # Add Python dependencies required by
    # rutgers_agx_arm and rutgers_ur5e here.
]
piper = [
    "python-can>=3.3.4",
    "typing-extensions>=3.7.4.3",
]


[project.scripts]
ruri-server = "ruri.server.__main__:main"
ruri-client = "ruri.client.__main__:main"


[tool.setuptools.packages.find]
where = ["src", "vendor/pyAgxArm"]
include = ["ruri*", "pyAgxArm*"]


[tool.setuptools.package-data]
"ruri.client.controllers.single_piper" = [
    "cam_params.json",
    "mit/assets/*.json",
    "mit/assets/*.urdf",
    "mit/assets/LICENSE*",
]
