[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"


[project]
name = "rutgers-robot-inference"
version = "0.1.0"
description = "A minimal inference stack for robot policies."
readme = "readme.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "pyzmq",
    "msgpack",
]


[project.optional-dependencies]
client = [
    # Add Python dependencies required by
    # rutgers_agx_arm and rutgers_ur5e here.
]


[project.scripts]
ruri-server = "ruri.server.__main__:main"
ruri-client = "ruri.client.__main__:main"


[tool.setuptools.packages.find]
where = ["src"]
